### PR TITLE
Support mongoose 5.0.x

### PR DESCRIPTION
**Pull request by Ben305**
Add support for mongoose 5.0.x

### CODE REVIEW

**Comment by Ben305** [comment]
@drudge Hey, could you merge this and publish it to npm? I'd really appreciate that 👍

**Comment by richarddd** [comment]
@drudge I have a PR for typegoose relying on this to be merged. Please merge :)

**Comment by DavidBernal** [comment]
Pls merge and update npm package.

**Comment by DavidBernal** [comment]
Pls merge and update npm package.

**Comment by drudge** [comment]
Published to npm as 3.0.0.

**Pull request merged**
