### PR TITLE
Fix "TypeError: Cannot read property 'indexOf' of undefined"

### PR DESCRIPTION
**Pull request by FdezRomero**
Checks that `JSON.stringify(conditions[keys[z]])` is not `undefined` before calling `indexOf` on line 57.

### CODE REVIEW

**Comment by FdezRomero** [comment]
Fixes #15 as well.

**Comment by propan** [comment]
@drudge are you planning to release a new version that contains the fix?

**Comment by ORESoftware** [comment]
@drudge return to the fold

**Comment by iykedapotential** [comment]
@drudge please when are we releasing a new version with this fix. It is currently breaking my code.

**Pull request merged**
