### PR TITLE
Adding in promise support 

### PR DESCRIPTION
**Pull request by clarkieryan**
This update breaks no existing features, but if no callback is provided then the findOrCreate() function will return a promise to the developer.

### CODE REVIEW

**Comment by igordeoliveirasa** [comment]
How can I install this version?

**Comment by drudge** [comment]
@clarkieryan Any reason you are only testing on Node 5.3?

**Comment by clarkieryan** [comment]
@drudge Testing only on 5.3 as this version provides native promise support - support can be added for the other versions - with the use of shims - haven't had the time to do this. 

@igordeoliveirasa You can use the clarkieryan/mongoose-findorcreate repo to install this build of find-or-create.

**Comment by drudge** [comment]
That's fine, @clarkieryan. I don't plan on merging this in without support for previous versions of node. Feel free to submit another PR when you've had time

**Comment by manakor** [comment]
Would be awesome if `Model.findOrCreate()` returned a promise&zwnj;_!_
Many people use promises in their daily development, others already switching to ES7's `switch`/`async` with Babel — promises usage is getting dominance.

**Comment by drudge** [comment]
@manakor I'd gladly merge in promise support that supported all the tests of the current version.

**Comment by clarkieryan** [comment]
Yeah, I was using native promises on the latest version of nodejs - understandable to make sure it's supported on previous versions - will probably convert the current pull request to use es6-promise.

**Comment by clarkieryan** [comment]
@drudge Hey - all tests are failing on 0.8 of node - mongoose now only supports 0.10+ can we remove 0.8 from the tests? Then release promises as a version bump?

**Comment by manakor** [comment]
@clarkieryan, I think [`es6-promise`](https://www.npmjs.com/package/es6-promise) library shall be supporting 0.8 without an issue. Or you decided to rely only on native promises?

**Comment by clarkieryan** [comment]
@manakor https://travis-ci.org/clarkieryan/mongoose-findorcreate/jobs/120838264 as far as I can tell it was failing when trying to install - I ended up using bluebird promises https://github.com/clarkieryan/mongoose-findorcreate

**Pull request closed without merging**
